spring.application.name=OrbitControl

spring.datasource.url=jdbc:mysql://localhost:3306/orbitcontroltfgbd?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Ejecuta schema.sql antes de que Hibernate haga el DDL (elimina tablas legacy)
spring.sql.init.mode=always

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# node -e "console.log(require('crypto').randomBytes(64).toString('base64'))
jwt.secret=3HaRgHdiIb7qc1xolR0X14JlFEOlju5YmY9cgvqXUdIaiF1sQFBAs0crlCCPFpfz4LwsJ4JDgpBtMZNQFQOIIA==
jwt.expiration=43200000

server.error.include-message=always